#Cloudinary settings. account is main gmail
cloudinary.cloud_name=dg6e4oagz
cloudinary.api_key=327479359135169
cloudinary.api_secret=yuXdWJsIKRnNpNv1pEKUb7K2ZTk




spring.application.name=campusmarket
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test










spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#
#spring.jpa.hibernate.ddl-auto=update